### ISSUE TITLE
Incompatibility with Forestry"

### ISSUE THREAD

**Issue by kittykatekk** [RootsTeam/Goetia#11]
Hello!
I've discover one strange incompatibility of your mod "Goetia" and "Forestry".
When I thumb over pages of JEI and look on some mod things all my interface is gone out, including jei, pause menu, etc. After some search I found incompatibility with Forestry, and when I turn off some modules of Forestry, exactly "Storage" module, error is gone and everything start work normal.
I use Forge 12.18.2.2122, Goetia 0.3.2 and Forestry 5.2.16.327.
Please sorry my english and good luck with your mods, Team Roots!

**Comment by kittykatekk** [comment]
I'm sorry I don't look at the "closed" issues before start new, but someone wrote this problem not fixed and maybe my description can help

**Comment by werty1124** [comment]
I thought i had this fixed but people are reporting it again. Your information is helpful had no idea about disabling certain modules making the errors stop

**Comment by elucent** [comment]
I believe I have found a solution. I'm busy so I can't test it now, but I've notified the team members working on this project over Discord.

Specifically, the GlStateManager.popMatrix(); call at https://github.com/RootsTeam/Goetia/blob/master/src/main/java/teamroots/goetia/common/GeneralEventHandler.java#L125 should be swapped with the GlStateManager.pushMatrix() call below it.

**Comment by AnZaNaMa** [comment]
fixed by @ShadowGamerXY
