### ISSUE TITLE
Server crash on launch with 0.3.

### ISSUE THREAD

**Issue by dahjin** [RootsTeam/Goetia#4]
I believe it's 
`net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/statemap/IStateMapper`

http://pastebin.com/FMGEK482

**Comment by Febilian** [comment]
I'm getting this as well. :') Guess I'll have to wait before sticking it in my modset after all.

**Comment by werty1124** [comment]
I'll fix this ASAP looks like I overlooked something and didn't test Goetia on servers properly

**Comment by werty1124** [comment]
Fixed in 0.3.1

**Comment by Febilian** [comment]
Appreciate the time you're putting into this. Any idea of a timeframe for when 0.3.1 might be available for download? No rush, just trying to plan ahead.

**Comment by werty1124** [comment]
It was uploaded as soon as I commented :p

**Comment by Febilian** [comment]
Derp. Whoops.
