### ISSUE TITLE
Several placed note shenanigans/issues

### ISSUE THREAD

**Issue by Febilian** [RootsTeam/Goetia#5]
1. A note placed against the side of a block will end up on top of that block , even if it has to delete the block already above it to do so.

2. I placed a WIP angel note by right clicking it on a block; breaking it/picking it up again turned it into a demon note instead.

On a side note: If the angel notes are at all functional, it's pretty impossible to figure out what each one does because they all have the same "WIP" description on them. =P

**Comment by werty1124** [comment]
This should be an easy fix

**Comment by werty1124** [comment]
Also fixed!
