### ISSUE TITLE
Can't use more than one angelic lost note

### ISSUE THREAD

**Issue by Febilian** [RootsTeam/Goetia#6]
I checked advanced tooltips, and they all appear to have different metadata values and I'm guessing therefore should have different things to learn, but since the first one I learned/consumed, I can't use any more of them for some reason.

I'm on a dedicated server, but there doesn't appear to be anything in the client or server logs when this is happening, so I'm afraid I'm not sure what other information to provide.

**Comment by werty1124** [comment]
Nope they're all WIP. While you are correct they all have different meta values all the knowledge is "WIP" so after you learn "WIP" you can no longer learn it again. They will hopefully fully implemented in the next full update

**Comment by Febilian** [comment]
Oh, okay! Just found it a bit odd that they were already generating as dungeon loot if they weren't functional is all. =p

**Comment by werty1124** [comment]
I put them in as dungeon loot as a WIP because they can still be used as decoration :)

**Comment by Febilian** [comment]
Ah, I see. Question: Will the notes become functional when they are implemented, i.e. are they worth saving for later if not for decoration?

**Comment by werty1124** [comment]
Yes, they should take on the appropriate knowledge for their meta value once they are actually functional

**Comment by Febilian** [comment]
Awesome, good to know. I'll hang onto them then(assuming this world lasts that long. I tend to go through MC worlds like hotcakes haha).
