### ISSUE TITLE
Shift-right-clicking demonic chalk on server causes client to crash

### ISSUE THREAD

**Issue by Febilian** [RootsTeam/Goetia#7]
This time seems to be trouble getting a GUI texture for the chalk interface somehow. There wasn't anything on the server's log, so here's the crash report.

It said I don't have anything learned as well, even though I'd consumed a few demon notes already from dungeons.

https://gist.github.com/Febilian/f5448897a3c74c59de0959d2103820b4

Also I'm really hoping all these bug reports aren't too annoying!

EDIT: I just tested this in single player as well. It didn't crash using the chalk until I learned an angel knowledge note, THEN it crashed on shift-right-click. I think it has to do with the knowledge storage of the recently added purity-aligned things.

**Comment by werty1124** [comment]
The bug reports are very helpful! Keep themem coming!

As for the crash that's odd it _was_ working fine for me when I tested earlier. I'll take another look at it

**Comment by Febilian** [comment]
I tried learning a demonic note before the angelic one, if it helps. So I had both angelic and demonic knowledge at that point when I tried to use the chalk.

**Comment by werty1124** [comment]
Hmm odd

**Comment by Febilian** [comment]
Yeah, I deleted the file for the angelic 'WIP' knowledge in my player-data file using a NBT editor, and now I can use the chalk without crashing. AKA I only have demonic knowledge now.

**Comment by werty1124** [comment]
Alriight thats helpful info

**Comment by werty1124** [comment]
Fixed
