### ISSUE TITLE
Lost notes found in chests change their knowledge when put into inventory

### ISSUE THREAD

**Issue by Febilian** [RootsTeam/Goetia#9]
For example, I found a "Summon Demon" note generated in a dungeon chest and it turned into "Soul Forge" when I picked it up; I found this out because I tried to learn it and nothing happened, and then when I looked at the name it was different.

I don't know if there's any rhyme or reason to this, I'll keep track of what notes turn into in the future as I come across them if it helps.

**Comment by werty1124** [comment]
Odd haven't noticed that happening to me after testing for a bit I'll keep seeing if I can figure it out though

**Comment by squirrelkiller** [comment]
Might be an issue with how you are storing what the notes are, can't tell if you are storing them as NBT or Meta, but meta is typically harder to have change weirdly than NBT.

**Comment by elucent** [comment]
Meta is required for them to randomly show up in dungeon chests. I couldn't find a way to make random NBT show up in a vanilla-style loot table.

**Comment by AnZaNaMa** [comment]
This should be fixed now. Let me know if there are any more issues with it.
